// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulkbclgngyxmkbygzlxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsa2JjbGduZ3l4bWtieWd6bHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2MTQ2OTgsImV4cCI6MjA5NzE5MDY5OH0.9OQ4Zhfg__WJ2_-0JuDxaTZC_8eu6GzLFrcv4qthaKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});